### ISSUE TITLE
 Can't find model 'en_core_web_sm'

### ISSUE THREAD

**Issue by fengsky401** [fudan-zvg/Semantic-Segment-Anything#10]
python scripts/main.py  --data=image_20230408/ --out_dir output --world_size=1  --save_img
Traceback (most recent call last):
  File "scripts/main.py", line 4, in <module>
    from pipeline import semantic_annotation_pipeline
  File "/data2/queenie_2023/Semantic-Segment-Anything/scripts/pipeline.py", line 13, in <module>
    from blip import open_vocabulary_classification_blip
  File "/data2/queenie_2023/Semantic-Segment-Anything/scripts/blip.py", line 3, in <module>
    from utils import get_noun_phrases
  File "/data2/queenie_2023/Semantic-Segment-Anything/scripts/utils.py", line 2, in <module>
    nlp = spacy.load('en_core_web_sm')
  File "/data2/queenie/anaconda3/envs/mmTrans/lib/python3.7/site-packages/spacy/__init__.py", line 60, in load
    config=config,
  File "/data2/queenie/anaconda3/envs/mmTrans/lib/python3.7/site-packages/spacy/util.py", line 449, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**Comment by Divyansh-0** [comment]
You can try the command python -m spacy download en_core_web_sm

**Comment by lzrobots** [comment]
Please refer to the **Installation** section and run python -m spacy download en_core_web_sm.

**Comment by wzr0108** [comment]
en_core_web_sm的哪个版本

**Comment by wzr0108** [comment]
en_core_web_sm的哪个版本
