### ISSUE TITLE
cannot import print.log from mmcv.util using google colab

### ISSUE THREAD

**Issue by sulaiman1988** [fudan-zvg/Semantic-Segment-Anything#48]
Traceback (most recent call last):
  File "/content/Semantic-Segment-Anything/scripts/main_ssa_engine.py", line 5, in <module>
    from pipeline import semantic_annotation_pipeline
  File "/content/Semantic-Segment-Anything/scripts/pipeline.py", line 8, in <module>
    from mmcv.utils import print_log
ImportError: cannot import name 'print_log' from 'mmcv.utils' (/usr/local/lib/python3.10/dist-packages/mmcv/utils/__init__.py)

**Comment by sulaiman1988** [comment]
where is the requirements file?

**Comment by ayaan-mphasis** [comment]
I am having the same issue, did you find any solution?

**Comment by lywang76** [comment]
> I am having the same issue, did you find any solution?

change it to
from mmengine import print_log

**Comment by georgeguida** [comment]
any alternatives to this? 

Still get this after running from mmengine import print_log:

/content/drive/MyDrive/AI/Semantic-Segment-Anything
Traceback (most recent call last):
  File "/content/drive/MyDrive/AI/Semantic-Segment-Anything/scripts/main_ssa.py", line 6, in <module>
    from pipeline import semantic_segment_anything_inference, eval_pipeline, img_load
  File "/content/drive/MyDrive/AI/Semantic-Segment-Anything/scripts/pipeline.py", line 5, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

This also does not work in colab currently:

!pip3 install openmim
!mim install mmcv-full 
#https://mmdetection.readthedocs.io/en/dev/get_started.html
