### ISSUE TITLE
torch and transformers version mismatch error

### ISSUE THREAD

**Issue by ruiqixu37** [fudan-zvg/Semantic-Segment-Anything#54]
Hi, when I tried to run SSA inference, I met this following error:

> Traceback (most recent call last):
  File "scripts/main_ssa.py", line 122, in <module>
    main(0, args)
  File "scripts/main_ssa.py", line 66, in main
    from transformers import SegformerFeatureExtractor, SegformerForSemanticSegmentation
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/rxu37/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1117, in __getattr__
    value = getattr(module, name)
  File "/home/rxu37/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/rxu37/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.segformer.modeling_segformer because of the following error (look up to see its traceback):
No module named 'torch.distributed.algorithms.join'

I installed my environment using the exact provided `environment.yaml` , so my torch version is 1.9.1+cu111, and my transformers version is 4.27.1. I looked up the PyTorch doc and found that only PyTorch 2.0 has the module `torch.distributed.algorithms.join`. Thus I upgraded PyTorch to 2.0.1+cu118, but now I met the error 

> Traceback (most recent call last):
  File "scripts/main_ssa.py", line 6, in <module>
    from pipeline import semantic_segment_anything_inference, eval_pipeline, img_load
  File "/mnt/d/GitHub/Semantic-Segment-Anything/scripts/pipeline.py", line 8, in <module>
    from mmdet.core.visualization.image import imshow_det_bboxes
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/rxu37/anaconda3/envs/ssa/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

I have tried to rebuild the mmcv module after I upgrade torch, but it does not seem to work. Would greatly appreciate any pointer/help on this issue. Thank you!

**Comment by ruiqixu37** [comment]
I solved the issue by rebuilding both `mmcv-full` (not `mmcv`) and `mmdet` modules. My `mmcv-full` version is 1.6.0 and my `mmdet` version is 2.25.3. My `torch` version is 2.0.1+cu118. Any `mmcv` version greater than 1.6.0 will make the scripts fail. Hope this helps people who met the same issue as I did! 

Also I would suggest changing the corresponding default environment configurations? It seems I am the only one yet who met this version error though.
